# For elasticsearch
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elasticsearch
spec:
  storageClassName: local-storage
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/elasticsearch"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-server
spec:
  storageClassName: local-storage
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus-server"    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alert-manager
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/prometheus-alert-manager"    